def ENV_NAME = ""
def BUILD_SCRIPT = ""
def ENV_PORT = 0

pipeline {
    agent any
    
    stages {
        stage("Code Quality SonarQube") {
            steps {
                sh 'sonar-scanner'
            }
        }
        stage("Environment Variables") {
            steps {
                script {
                    def branchName = scm.branches[0].name
                    echo "Branch Name: ${branchName}"

                    if (branchName == "*/main") {
                        ENV_NAME = "prod"
                        BUILD_SCRIPT = "build-prod"
                        ENV_PORT = 8000
                    } else if (branchName == "*/release") {
                        ENV_NAME = "preprod"
                        BUILD_SCRIPT = "build-preprod"
                        ENV_PORT = 8001
                    } else {
                        ENV_NAME = 'develop'
                        BUILD_SCRIPT = "build-develop"
                        ENV_PORT = 8002
                    }
                }
            }
        }
        stage("Build") {
            steps {
                script {
                    sh "bun install"
                    sh "bun run '$BUILD_SCRIPT'"
                }
            }
        }
        stage("Build Custom NGINX image") {
            steps {
                script {
                    sh "docker build -t groupe7archiweb/thetiptop-front-'$ENV_NAME'-nginx-image ."
                }
            }
        }
        stage("Stop NGINX Container") {
            steps {
                script {
                    sh "docker rm -f thetiptop-front-'$ENV_NAME'"
                }
            }
        }
        stage("Deploy NGINX Container") {
            steps {
                script {
                    sh "docker run --rm -p '$ENV_PORT':80 --name thetiptop-front-'$ENV_NAME' -d groupe7archiweb/thetiptop-front-'$ENV_NAME'-nginx-image"
                }
            }
        }
    }
}

